{% set name = "prefect-docker" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/prefect_docker-{{ version }}.tar.gz
  sha256: 4b8d51d724d69eabab1fc225dae552ce2315d6be30cd5a8be1b548aadf3b8580

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - prefect >=2.13.5
    - docker-py >=6.1.1

test:
  imports:
    - prefect_docker
# Disable `pip check` until `prefect` adds `pip check` support
#  commands:
#    - pip check
#  requires:
#    - pip

about:
  home: https://github.com/PrefectHQ/prefect/tree/main/src/integrations/prefect-docker
  summary: Prefect integrations for interacting with Docker.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - peterbygrave
    - mikeoconnor0308
