{% set name = "prefect-docker" %}
{% set version = "0.6.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/prefect_docker-{{ version }}.tar.gz
  sha256: fd9a927b36d4b86ccbfd810688b186be07a0b2c99afbae5864aaec89963fa078

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - prefect >=3.0.0
    - docker-py >=6.1.1
    - exceptiongroup

test:
  requires:
    - python {{ python_min }}
  imports:
    - prefect_docker
# Disable `pip check` until `prefect` adds `pip check` support
#  commands:
#    - pip check
#  requires:
#    - pip

about:
  home: https://github.com/PrefectHQ/prefect/tree/main/src/integrations/prefect-docker
  summary: Prefect integrations for interacting with Docker.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - peterbygrave
    - mikeoconnor0308
